### PR TITLE
Updates drush to fix install error

### PR DESCRIPTION
**Pull request by kimpepper**

### CODE REVIEW

**Comment by jibran** [comment]
Why not do this and remove `composer.lock`?
```diff
diff --git a/build.xml b/build.xml
index ed471bb..50b9181 100644
--- a/build.xml
+++ b/build.xml
@@ -52,7 +52,7 @@
   <!-- Prepare the project -->
   <target name="prepare"
           description="Prepare for build">
-    <exec command="composer install --prefer-dist"
+    <exec command="composer update --prefer-dist"
           logoutput="${test.output}"
           passthru="${test.passthru}" />
   </target>
```

**Comment by kimpepper** [comment]
To have more control of updates.

However, Drush is following Drupal so it usually needs the update.

On 2 October 2015 at 21:36, Jibran Ijaz <notifications@github.com> wrote:

> Why not do this and remove composer.lock?
>
> diff --git a/build.xml b/build.xml
> index ed471bb..50b9181 100644--- a/build.xml+++ b/build.xml@@ -52,7 +52,7 @@
>    
>    <target name="prepare"
>            description="Prepare for build">-    <exec command="composer install --prefer-dist"+    <exec command="composer update --prefer-dist"
>            logoutput="${test.output}"
>            passthru="${test.passthru}" />
>    </target>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/nickschuch/vd8/pull/36#issuecomment-145192000>.
>



-- 
Kim Pepper
Technical Director
PreviousNext

desk: 02 8005 8670
mobile: 0414 212 530
skype: kim.pepper

**Comment by nickschuch** [comment]
Yeah, just the other dependencies eg. Phing that we want to keep track of.

**Comment by jibran** [comment]
See #40

**Pull request closed without merging**
