### PR TITLE
Composer update

### PR DESCRIPTION
**Pull request by kimpepper**
Composer update for drush to avoid ContainerNotInitializedException on phing login.
Version dependencies for coder have also been updated.

### CODE REVIEW

**Comment by jibran** [comment]
I think we should remove composer.lock file.

**Comment by nickschuch** [comment]
Im not sure about removing it @jibran. Sounds like chaos! :)

**Comment by nickschuch** [comment]
@jibran Why should we remove the .lock file?

**Comment by jibran** [comment]
drush is broken according to current lock file I have to run `composer update` to fix the `drush`. Now I can use local clone drush:master so I think doesn't matter whether we keep it or not. However, phing use VM drush so to fix that we have to upate the drush to latest master.

**Comment by nickschuch** [comment]
Should we be locking into a specific version of composer or just chase HEAD? Chasing HEAD has been a bit tricky on the DrupalCI projects.

**Comment by jibran** [comment]
I think we can close it now after #32

**Pull request closed without merging**
